version: "3"

networks:
  virhal_ctl:
    driver: overlay

services:
    agent:
        image: opny/virhal
        # image: opny/virhal
        build: .
        command: /virhal agent --debug
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
          - "12832:12832"
        networks:
            - virhal_ctl
