version: "1"
services:
    webapp:
        tags:
            arch: x86
            type: cloud
        mode: compose # or container, swarm, function
        file: ./examples/webapp.yml
    api1:
        tags:
            arch: armhf
            ble: 1
        mode: container
        #format is the same as per compose `service` definition
        # file: ./examples/container.yml
        service:
            image: nginx
