package project_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/muka/virhal/api/models"
)

// StopReader is a Reader for the Stop structure.
type StopReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewStopOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewStopOK creates a StopOK with default headers values
func NewStopOK() *StopOK {
	return &StopOK{}
}

/*StopOK handles this case with default header values.

StopOK stop o k
*/
type StopOK struct {
	Payload *models.VirhalResponse
}

func (o *StopOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/project/{Name}][%d] stopOK  %+v", 200, o.Payload)
}

func (o *StopOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VirhalResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
