package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// VirhalService virhal service
// swagger:model virhalService
type VirhalService struct {

	// file
	File strfmt.Base64 `json:"File,omitempty"`

	// mode
	Mode string `json:"Mode,omitempty"`

	// name
	Name string `json:"Name,omitempty"`

	// tags
	Tags map[string]string `json:"Tags,omitempty"`
}

// Validate validates this virhal service
func (m *VirhalService) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *VirhalService) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VirhalService) UnmarshalBinary(b []byte) error {
	var res VirhalService
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
